In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
import jieba 

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [5]:
data

array([[-9.42161046e-01, -2.76421542e-01,  7.86028535e-01,
         6.17738631e-01],
       [ 1.17979471e-01, -8.11651815e-01,  5.75120119e-01,
        -1.39744879e+00],
       [-3.13997073e-01, -6.37053095e-01, -6.16699723e-01,
        -3.50153303e-01],
       [ 1.40032583e+00,  1.18696639e+00,  1.02013460e+00,
         5.58161090e-01],
       [ 4.14304071e-01,  5.31217544e-03,  8.48961199e-01,
         6.07365296e-01],
       [-1.35420953e+00, -4.97653300e-01, -6.76006930e-01,
         1.61859961e-04],
       [-1.91530848e+00, -1.13650904e+00,  1.22244104e+00,
        -1.20568144e+00]])

In [6]:
#跟算术运算⼀样，数组的⽐较运算（如==）也是⽮量化的
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
#布尔型数组可⽤于数组索引
data[names == 'Bob']

array([[-0.94216105, -0.27642154,  0.78602854,  0.61773863],
       [ 1.40032583,  1.18696639,  1.0201346 ,  0.55816109]])

In [9]:
#布尔型数组的⻓度必须跟被索引的轴⻓度⼀致。此外，还可以将布尔型数组跟切⽚、整数（或整数序列）混合使⽤
data[names == 'Bob', 2:]

array([[0.78602854, 0.61773863],
       [1.0201346 , 0.55816109]])

In [12]:
data[names == 'Bob', 3]

array([0.61773863, 0.55816109])

In [13]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [14]:
data[~(names == 'Bob')]

array([[ 1.17979471e-01, -8.11651815e-01,  5.75120119e-01,
        -1.39744879e+00],
       [-3.13997073e-01, -6.37053095e-01, -6.16699723e-01,
        -3.50153303e-01],
       [ 4.14304071e-01,  5.31217544e-03,  8.48961199e-01,
         6.07365296e-01],
       [-1.35420953e+00, -4.97653300e-01, -6.76006930e-01,
         1.61859961e-04],
       [-1.91530848e+00, -1.13650904e+00,  1.22244104e+00,
        -1.20568144e+00]])